### ISSUE TITLE
Backward direction of the simulation failed

### ISSUE THREAD

**Issue by EduAFlores** [ichthyop/ichthyop#44]
Hi all,
I'm using Ichthyop v3.2 (and Apache NetBeans IDE 12.3) and I tried to run a simulation with backward direction but fail with this message. 

org.previmer.ichthyop.ui.SFTask failed
SEVERE: -1
java.lang.ArrayIndexOutOfBoundsException: -1
	at org.previmer.ichthyop.dataset.Roms3dDataset.get_dUx(Roms3dDataset.java:469)
	at org.previmer.ichthyop.action.AdvectionAction.advectEuler(AdvectionAction.java:88)
	at org.previmer.ichthyop.action.AdvectionAction.advectBackward(AdvectionAction.java:124)
	at org.previmer.ichthyop.action.AdvectionAction.execute(AdvectionAction.java:62)
	at org.previmer.ichthyop.manager.ActionManager.executeActions(ActionManager.java:103)
	at org.previmer.ichthyop.particle.MasterParticle.step(MasterParticle.java:110)
	at org.previmer.ichthyop.Population.step(Population.java:63)
	at org.previmer.ichthyop.Simulation.step(Simulation.java:27)
	at org.previmer.ichthyop.ui.IchthyopView$SimulationRunTask.doInBackground(IchthyopView.java:1081)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

 I did the backward test with the Benguela simulations and works fine, but with my CROCO model it doesn't work. I did several others experiments with forward direction and everything works fine, only with the backward configuration failed.

I would appreciate if someone knows how to solve this,
Eduardo A. Flores

**Comment by barriern** [comment]
Hi Eduardo.

Could you please send me your configuration files (XML files) and some of your forcing files? I don't need all the time-steps but I need some in order to see what happens. 

Thanks

Nicolas
