### ISSUE TITLE
error Java JDK version with the new Ichthyop version 3.3.16

### ISSUE THREAD

**Issue by CelineBarrier** [ichthyop/ichthyop#74]
Hello,

With older versions of Ichthyop, I used to send my parallelized simulations launched in slurm to a java executable like javaJDK/jdk1.8.0_66. Today, I run some simulations with version 3.3.16 and with this javaJDK I have the error below (je joins également la config .xml et le slurm si besoin).

[Squinado_mars_2010.txt](https://github.com/ichthyop/ichthyop/files/11834840/Squinado_mars_2010.txt)
[simu_dev.txt](https://github.com/ichthyop/ichthyop/files/11834841/simu_dev.txt)

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/previmer/ichthyop/ui/IchthyopApp has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

**Comment by barriern** [comment]
Hi @CelineBarrier 

Indeed, the newest version of Ichthyop runs on JDK 11 (at least). Which is why you have this error (you are using JDK 8)

To solve this, either ask the admin of your HPC to install a newest version of Java. Another possibility is to use Conda (if installed on the HPC) to create an appropriate Java environment for Ichthyop

Nicolas

**Comment by CelineBarrier** [comment]
Hello, 
That is what I did, thank you !
